### ISSUE TITLE
Washington Post fails to download

### ISSUE THREAD

**Issue by andrewgaul** [kebernet/shortyz#114]
It appears that the location needs updating:

```
08-19 00:30:11.779 6267-11612/com.totsp.crossword.shortyz I/com.totsp.crossword: Downloading from https://washingtonpost.as.arkadiumhosted.com/clients/washingtonpost-content/SundayCrossword/mreagle_170702.xml
08-19 00:30:12.275 6267-11612/com.totsp.crossword.shortyz I/System.out: Not zipped
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err: org.apache.harmony.xml.ExpatParser$ParseException: At line 75, column 0: junk after document element
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:515)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at com.totsp.crossword.io.JPZIO.readPuzzle(JPZIO.java:120)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at com.totsp.crossword.io.JPZIO.convertJPZPuzzle(JPZIO.java:136)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at com.totsp.crossword.net.AbstractJPZDownloader.download(AbstractJPZDownloader.java:34)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at com.totsp.crossword.net.LATSundayDownloader.download(LATSundayDownloader.java:35)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at com.totsp.crossword.net.Downloaders.download(Downloaders.java:246)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at com.totsp.crossword.BrowseActivity$9.run(BrowseActivity.java:770)
08-19 00:30:12.277 6267-11612/com.totsp.crossword.shortyz W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by bjg222** [comment]
The WaPo crosseords is still not downloading.  If an alternative URL is needed, I've found it here: https://crosswordfiend.com/download/#sundays

It's tedious, but I've just been manually downloading it from there and dropping it in the crosswords folder.
