### ISSUE TITLE
Shortyz on SDK 7!

### ISSUE THREAD

**Issue by nmyshkin** [kebernet/shortyz#187]
Yeah, I know :-)  I'm looking to replace a failed crossword app on my Nook Simple Touch. Back in the day many users recommended Shortyz. I've downloaded every version that will install on Eclair. They get to the info/changes page and try some downloads (which fail). I'm not concerned about the downloads because I can get my own .puz files and put them in the "crosswords" folder. But I can't get past the opening screen. This is a constant feature of logcats for all the versions I've tried:
```
E/AndroidRuntime(15180): Caused by: java.nio.charset.UnsupportedCharsetException: The unsupported charset name is "Cp1252".
E/AndroidRuntime(15180): 	at java.nio.charset.Charset.forName(Charset.java:572)
E/AndroidRuntime(15180): 	at com.totsp.crossword.io.IO.<clinit>(IO.java:31)
```
Cp1252? It's hard to believe that older Nook firmwares had this (whatever it is) and then it got lost in later revisions). Can you shed some light on this?

**Comment by nmyshkin** [comment]
OK, so I "fixed" this by decompiling the app with Apktool. There was only one reference in all of the files to "Cp1252" (which research revealed to be an older Windows charset mapping. I replaced this with "utf-8" and recompiled. It works, although occasionally punctuation marks are not understood. From what I've read the mapping is not 100% the same for the two character sets, but this seems to be other than standard letters, so I think I can live with that.
