### ISSUE TITLE
ArrayIndexOutOfBoundsException in LA Times Nov 21, 2016

### ISSUE THREAD

**Issue by andrewgaul** [kebernet/shortyz#72]
When entering "bela" in 13-down:

```
java.lang.ArrayIndexOutOfBoundsException: length=15; index=15
       at com.totsp.crossword.puz.MovementStrategy$4.getIndexOfLargestWhitespace(MovementStrategy.java:332)                        at com.totsp.crossword.puz.MovementStrategy$4.move(MovementStrategy.java:266)
       at com.totsp.crossword.puz.Playboard.nextLetter(Playboard.java:492)
       at com.totsp.crossword.puz.Playboard.nextLetter(Playboard.java:496)                                                         at com.totsp.crossword.puz.Playboard.playLetter(Playboard.java:538)
       at com.totsp.crossword.PlayActivity.onKeyUp(PlayActivity.java:877)                                                          at com.totsp.crossword.PlayActivity$4.onKey(PlayActivity.java:288)
       at android.inputmethodservice.KeyboardView.detectAndSendKey(KeyboardView.java:828)
       at android.inputmethodservice.KeyboardView.onModifiedTouchEvent(KeyboardView.java:1351)                                     at android.inputmethodservice.KeyboardView.onTouchEvent(KeyboardView.java:1214)
       at android.view.View.dispatchTouchEvent(View.java:9300)                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2771)                                                              at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)                              at android.view.View.dispatchPointerEvent(View.java:9520)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(Native Method)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
```

**Comment by andrewgaul** [comment]
![screenshot_20161124-143738](https://cloud.githubusercontent.com/assets/848247/20610786/a427ee8e-b253-11e6-9285-30385288ddad.png)

**Comment by andrewgaul** [comment]
Verified fixed, thanks!
